CREATE SCHEMA IF NOT EXISTS rene; 				-- crear un nuevo schema 'rene' si no existe

CREATE TABLE IF NOT EXISTS rene.caduce( 		-- crear nueva tabla 'caduce' si no existe 
	id_caduce				INTEGER PRIMARY KEY,-- calve primaria de cadece
	caduce					VARCHAR (50)
);

CREATE TABLE IF NOT EXISTS rene.origen( 		-- crear nueva tabla 'origen' si no existe
	id_origen				INTEGER GENERATED BY DEFAULT AS -- identificador autoincremental de origen y clave primaria
	IDENTITY PRIMARY KEY,
	nombre_origen			VARCHAR (50) NOT NULL-- nombre del origen (campo obligatorio)
);

CREATE TABLE IF NOT EXISTS rene.talla( 			-- crear nueva tabla 'talla' si no existe
	id_talla				INTEGER GENERATED BY DEFAULT AS -- identificador autoincremental de talla y clave primaria
	IDENTITY PRIMARY KEY,
	tipo_talla				VARCHAR (20) NOT NULL -- descripcion del tipo de talla (campo obligatorio)
);

CREATE TABLE IF NOT EXISTS rene.categoria( 		-- crear nueva tabla 'categoria' si no existe
	id_categoria			INTEGER GENERATED BY DEFAULT AS -- identificador autoincremental de categoria y clave primaria
	IDENTITY PRIMARY KEY,
	nombre_categoria		VARCHAR (50) NOT NULL, -- combre de la categoria (campo obligatorio)
	id_caduce				INTEGER, 			-- referencia a tabla 'caduce'
	CONSTRAINT fk_categoria_caduce FOREIGN KEY (id_caduce)
	REFERENCES rene.caduce (id_caduce) 			-- denicion de foreign key hacia 'rene.caduce'
);

CREATE TABLE IF NOT EXISTS rene.productos(		-- crear nueva tabla 'productos' si no existe
	id_producto				INTEGER GENERATED BY DEFAULT AS -- identificador autoincremental de productos y clave primaria
	IDENTITY PRIMARY KEY,
	precio_unit				NUMERIC (10,2) NOT NULL, -- precio unitario de hasta 10 numero enteros con 2 decimales (campo obligatorio)
	id_categoria			INTEGER NOT NULL, -- referencia a tabla 'categoria'
	CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria)
	REFERENCES rene.categoria (id_categoria) -- definicion de foreign key hacia 'rene.categoria'
);

CREATE TABLE IF NOT EXISTS rene.ropa( 		-- crear nueva tabla 'ropa' si no existe
	id_ropa 				INTEGER GENERATED BY DEFAULT AS -- identificador autoincremental de ropa y clave primaria
	IDENTITY PRIMARY KEY,
	id_producto				INTEGER NOT NULL, -- referencia a tabla 'productos'
	CONSTRAINT fk_ropa_producto FOREIGN KEY (id_producto)
	REFERENCES rene.productos (id_producto)-- definicion de foreign key hacia 'rene.productos'
);

CREATE TABLE IF NOT EXISTS rene.comida(		-- crear tabla 'comida' si no existe
	id_comida				INTEGER GENERATED BY DEFAULT AS -- identificador autoincremental de comida y clave primaria
	IDENTITY PRIMARY KEY,
	id_producto				INTEGER NOT NULL, -- referencia a tabla 'productos'
	CONSTRAINT fk_comida_producto FOREIGN KEY (id_producto)
	REFERENCES rene.productos (id_producto) -- definicion de foreign key hacia 'rene.productos'
);

CREATE TABLE IF NOT EXISTS rene.ropa_talla(
    id_ropa INTEGER NOT NULL,
    id_talla INTEGER NOT NULL,
    CONSTRAINT fk_rt_ropa FOREIGN KEY (id_ropa)
    REFERENCES rene.ropa(id_ropa),
    CONSTRAINT fk_rt_talla FOREIGN KEY (id_talla)
    REFERENCES rene.talla(id_talla),
    PRIMARY KEY (id_ropa, id_talla)
);

CREATE TABLE IF NOT EXISTS rene.ropa_origen(
    id_ropa INTEGER NOT NULL,
    id_origen INTEGER NOT NULL,
    CONSTRAINT fk_ro_ropa FOREIGN KEY (id_ropa)
    REFERENCES rene.ropa(id_ropa),
    CONSTRAINT fk_ro_origen FOREIGN KEY (id_origen)
    REFERENCES rene.origen(id_origen),
    PRIMARY KEY (id_ropa, id_origen)
);

CREATE TABLE IF NOT EXISTS rene.comida_origen(
    id_comida INTEGER NOT NULL,
    id_origen INTEGER NOT NULL,
    CONSTRAINT fk_co_comida FOREIGN KEY (id_comida)
    REFERENCES rene.comida(id_comida),
    CONSTRAINT fk_co_origen FOREIGN KEY (id_origen)
    REFERENCES rene.origen(id_origen),
    PRIMARY KEY (id_comida,id_origen)
);