spring.application.name=mercado
# URL de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraciones de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Indica a Hibernate que use este esquema por defecto para crear/buscar tablas
spring.jpa.properties.hibernate.default_schema=rene
# ddl-auto: validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=none
# none = Desactiva completamente la gestión automática del esquema de la base de datos por parte de Hibernate. 
# Esto significa que no se crearán, actualizarán, validarán ni eliminarán tablas, 
# columnas ni índices durante el inicio de la aplicación.

# Mostrar SQL en consola (útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

